name: Release

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed


jobs:
  deploy:
    if: ${{ (github.event.workflow_run.conclusion == 'success') && (github.ref == 'refs/heads/master') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for "RELEASE:" in commit
        id: check-release
        run: |
          if [[ !($(git log -1 --pretty=format:"%s") =~ ^(RELEASE:)) ]]; then
            exit 1
          fi
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  tag:
    needs:
      deploy

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Get version
        run: |
          echo "VERSION=$(poetry version | cut -d' ' -f2)" >> $GITHUB_ENV
      - name: Tag master
        run: |
          git checkout master
          git tag v$VERSION
          git push origin v$VERSION



